### ISSUE TITLE
pose[] array is empty :(

### ISSUE THREAD

**Issue by sandeepkiks** [dahburj/Barracuda-PoseNet#2]
@dahburj  I have recent commented on [MlAgent issues](https://github.com/Unity-Technologies/ml-agents/issues/1825#issuecomment-493016286).
What I did is just cloned the repo and played the scene, poses[] array was empty. I might be missing something?
 As mentioned, if possible  can you please look into the build why it is not working. Running the same Unity version but on windows.

**Comment by dahburj** [comment]
Hey I just cloned the repo again and ran it using 2019.1.2f IOS build settings and it works, which scene are you opening? The correct scene is Assets/PoseNet/Scenes/Test. Also, I used a Texture Resize package I bought from the asset store which is excluded in this package, are you using that package (which would mean you bought it from the asset store) and if not what's your resize method? Perhaps your texture is corrupt after being resized.

**Comment by sandeepkiks** [comment]
Hey, my Unity version is 2019.1.2f Windows, and used  Assets/PoseNet/Scenes/Test scene. 
I am not using the Texture Resize package (from asset store) but using  a function which found in PoseNet-Unity repo found  [here](https://github.com/infocom-tpo/PoseNet-Unity/blob/8ae559d2bd5889f3a2380c3e619b8aef906d56fd/Assets/Sources/WebCameraExample.cs#L118)

The above resize function works well in that repo, not sure how it works in this this project (should work without any issue). 

But, resize is not the problem I guess. the error on [line 156 WebCameraExample.cs](https://github.com/dahburj/Barracuda-PoseNet/blob/a19c66bc97da189361243b8156ec7f0e4da1c24e/Assets/POSE-NET/Scripts/WebCameraExample.cs#L157) 
```"SetPixels32 called with invalid number of pixels in the array"``` 
One thing I did note that the buffer size is double than it should get. Example if the height is 413 and width is 705 then buffer is 413*705 =  291165 *2 = **582330**
Does this seem correct or the buffer should be double as above?

**Comment by dahburj** [comment]
I was going to ask Unity about that, I have the same problem, I played with the editor settings and switched the editor "Build Settings" to android, then to iOS, made sure Metal was enabled, re-imported the project, and that error went away. Now it works when my build settings are set to android or iOS but anything else is giving me the same error. I will try downloading and opening an earlier version Unity and try an earlier version of the project I have archived in my backup.

**Comment by dahburj** [comment]
[From repo clone to error hack](https://www.youtube.com/watch?v=UFlWXCrWbLc&feature=youtu.be)

I'm a little sick at the moment, so I haven't had time to properly debug the issue, however, I downloaded Unity v2018.1.0 and screen recorded everything that I did from repo-clone to getting it working in the editor (which was not much at all). The major bulk of the video consists of file downloads/unity importing, so my advice is to speed up the YouTube play speed and pause/slow down if something sticks out to you. I think there is a problem with calling the GPU camera buffer array with certain build settings, I will look into further tonight. I still don't understand why I never had this problem with Unity v2019.1.0b, maybe there was a bug in 2019.1.0b that worked to my advantage? A google search of the problem suggesting using two cameras in the scene and a RenderTexture to display the WebCam stream but even after trying that I'm seeing the same errors.

**Comment by sandeepkiks** [comment]
I too think "there is a problem with calling the GPU camera buffer array". Anyhow I have decided not to use GPU camera, rather I would use the `gpu_scale()` function. 
If I may suggest, use `if (webcamTexture.didUpdateThisFrame)` in your update as there is no meaning is processing old webcam frames.
Also, I would like to point that the FPS is been calculated in `Update()`. A good place calculate would be in `IEnumerator PoseUpdateNoTex(..) `
Thanks for all your efforts for looking into the issue. 
Cheers

**Comment by dahburj** [comment]
Honestly webcamtexture has been really bad (especially) on mobile devices, so I've been using the latest NatCam API; I'll have to see what the equivalent is to that call . I'm confused as to what you mean by old frames though, in the Update () function there is an IF statement with a Boolean condition that is set to True when the co-routine (PoseUpdateNoTex) begins, and false when it is has completed processing to avoid to avoid over running the hardware, I can't say I really understand how  barracuda works under the hood though, I mean any minor change to the yield wait time and performance is greatly effected. I followed Barracuda's documentation at first but that led to <10FPS. Arbitrarily setting the number and judging the scale of impact on performance led me to a 'magic number', but I was under the impression that Barracuda would run the tensor inference on other available threads (GPU/CPU) and return an answer without interrupting the main thread, I must be missing something. 

As far as the FPS, it crossed my mind to put it in PoseUpdateNoTex or FixedUpdate(), but I was sort of clueless as to which had the best accuracy, may I ask why that is the case? (to place it in PoseUpdateNoTex)

**Comment by sandeepkiks** [comment]
If you closely look at the the Posenet points, there is some lag (this is may be due to the delay in co-routine). The webcam frame is always ahead of the points. So even though the FPS is around 60, the points calculation is less than 60FPS.
