### ISSUE TITLE
For texture resizing You can use this:

### ISSUE THREAD

**Issue by TheBricktop** [dahburj/Barracuda-PoseNet#4]
https://pastebin.com/qkkhWs2J <- its resizing on gpu so its kinda fast

**Comment by dahburj** [comment]
Thank you! I'll try it out now

**Comment by dahburj** [comment]
Much appreciation for the script, the latest commit now includes the all the calls in the project's Assets/POSE-NET/Scripts/PoseNet/Util.cs script (A Partial PoseNet Class). I was pleased to see that it was just as fast as the plugin I was using, cheers!
