### ISSUE TITLE
Questions about how to convert Tensorflow model into proper .pb files and then .bytes or .nn files

### ISSUE THREAD

**Issue by cyz2727327** [dahburj/Barracuda-PoseNet#6]
Hi,

I have tried your project and it's running perfectly. Great job and congratz!

I'm trying to do similar things for my own project and I have encountered several issues when converting my own TensorFlow model first into .pb files then into .bytes or .nn files that can be loaded into Barracuda. I have a few questions for you and I would really hope you can give me some help.

- Right now I have a Tensorflow CNN model (version 1.14) already trained in the Python Jupyter environment, I have noticed that you might need a certain version of Tensorflow to train the model (something like 1.4.0 or 1.8.0) otherwise problems will appear. Is this still true for Barracuda? Do I need to downgrade my model and retrain in a different version?
- I was having some issues to create a frozen graph from my Tensorflow model, and I have noticed that different .pb files will result in different loading on the Unity side. Could you provide the python code you used to create the .pb model?
- After I have the .pb file, I just follow the official Barracuda manual and then load in the Unity environment. But unlike your model, upon loading, mine doesn't show the description of each layer, also even the layer number is different from the original model. So I'm wondering what did you do to convert your model that can be nicely-recognized and loaded by Barracuda.

Looking forward to hearing back from you. Thanks in advance.

**Comment by dahburj** [comment]
To be honest with you, the model was not my doing, I believe the link to the repo I used was included in the Readme that seems to have disappeared during the last commit, here's the link to the repo I used, https://github.com/rwightman/posenet-python.git, 
however, I can answer the question in regards to the layer names, just make sure you name the layers when developing your model. Now in regards to Tf1.14, I could write you a blog post. I was going through this months ago so my memory may be a bit hazy, however, if you're using Keras, you need to export the weights and the model arch. separately, and then clear the current graph and construct a new model using those exported variables and save/freeze that. However, there were many errors I ran into until I finally got it working that I can't really recall, I was using colab though so I can share the code I used that finally worked if you'd like to take a look and see what's going on. I was using tensorflow 2.0 to construct the model, then used tensorflow 1.14 to freeze it. Take a look at this repo as well, https://github.com/mantasp/barracuda-release
it helped me a lot.
