### ISSUE TITLE
Issue running on IPhone X

### ISSUE THREAD

**Issue by andyspeak1993** [dahburj/Barracuda-PoseNet#7]
hey your project works great on mac and pc but i cant get it to work on ios

any tips??

**Comment by dahburj** [comment]
Did you try building it in debug mode, there are a couple of plugin I use to debug issues like this but I don't think they're available in the repo, 

https://github.com/SpaceMadness/lunar-unity-console
https://github.com/yasirkula/UnityRuntimeInspector

I can't remember if I tested it on an iPhoneX I'll have to check the read me, I do remember it working on my Ipad. My brother has an IphoneX, worst comes to worst share some details and I'll get my hands dirty with you and try to run it using the same configuration and steps. I just need to know your setup, and what you're seeing in the Lunar Console on screen during run time (you'll have to add it to the scene and re build). It's honestly so frustrating trying to keep up with all these Unity updates, it's like for every version there are things a project needs that just will not work but used to and things that work but are faulty in the next version, I really just want to have my own version at this point I wonder if they have their open source one laying around somewhere.

**Comment by andyspeak1993** [comment]
hey sorry for the late response i haven't lost interest just busy with other thing.

i will try getting you some debug logs but it was a hard crash so not sure what will be available.

yeah always issues with preview versions i have noticed some huge differences between 7 and 6.3 would not recommend tying to update to 7 right now

and thanks for the response

**Comment by andyspeak1993** [comment]
Hey Dahbur here's the logs. let me know if you have any ideas on what my next step should be

2020-05-26 12:00:20.103798+0100 NewPoseNet[1372:230848] System version: 130500
2020-05-26 12:00:20.157653+0100 NewPoseNet[1372:230848] LUNAR/ASSERT: (image != nil) in /Barracuda-PoseNet-master/Assets/LunarConsole/Editor/iOS/Common/Utils/LUImageUtils.m:28 LUGetImage message:'Can't load image: lunar_console_action_button_large_normal'
2020-05-26 12:00:20.158080+0100 NewPoseNet[1372:230848] LUNAR/ASSERT: (image != nil) in /Barracuda-PoseNet-master/Assets/LunarConsole/Editor/iOS/Common/Utils/LUImageUtils.m:28 LUGetImage message:'Can't load image: lunar_console_action_button_large_selected'
2020-05-26 12:00:20.171190+0100 NewPoseNet[1372:230848] Built from '2019.3/staging' branch, Version '2019.3.0f3 (6c9e2bfd6f81)', Build type 'Release', Scripting Backend 'il2cpp'
-> applicationDidFinishLaunching()
-> applicationDidBecomeActive()
GfxDevice: creating device client; threaded=1
Initializing Metal device caps: Apple A12X GPU
Initialize engine version: 2019.3.0f3 (6c9e2bfd6f81)
UnloadTime: 0.041250 ms
Made it to the end of start 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

Setting up 2 worker threads for Enlighten.
  Thread -> id: 16cf23000 -> priority: 1 
  Thread -> id: 16cfaf000 -> priority: 1 
2020-05-26 12:00:21.322374+0100 NewPoseNet[1372:230848] [Common] _BSMachError: port 13f03; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
2020-05-26 12:00:21.323783+0100 NewPoseNet[1372:230848] Unbalanced calls to begin/end appearance transitions for <SplashScreenController: 0x104e3fca0>.

**Comment by dahburj** [comment]
I am so sorry it's taking this long, but I've just been diagnosed with this recently; `https://www.ehlers-danlos.com/eds-types/#Hypermobile-EDS`
and it was really only because of my visit to an ortho to complain about my shoulders dislocating and subloxing whenever I try and work, it's gotten to the point where my rib is even popping out when Im trying to use the mouse :( I will try and get to this as soon as my pain is just back into bearable levels, I honestly thought I could even avoid bringing this up and that I would be able to get to it any day now, however, I realized 9 days with an issue that's been open for 20 days requires a response; please accept my excusement stead my solution this time, and I promise to get back to you the second I am able.

**Comment by dahburj** [comment]
Hey again, forgive me for my tiny "vacation", but I'm curious if you ever did get this running?  I tested it again on an iOS device recently and didn't see any of those errors, but then again I built it in dev mode with Lunar console uncommented out (I noticed you built for dev) my release build test didn't have any debug libraries/etc. I would test a build but again (I have a horrible habit of dropping things)  I have no access to a iOS device (at least not any functional😂) at this present moment, I ran my last on a friends' device.🤷🏻‍♂️

**Comment by dahburj** [comment]
Marking issue closed for now I guess🤷🏻‍♂️
